INSERT INTO quotes (id, quote, author) VALUES
(1, 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'Robert Collier'),
(2, 'La mejor manera de predecir el futuro es creándolo.', 'Peter Drucker'),
(3, 'No cuentes los días, haz que los días cuenten.', 'Muhammad Ali'),
(4, 'La vida es 10% lo que te ocurre y 90% cómo reaccionas a ello.', 'Charles R. Swindoll'),
(5, 'Haz lo que puedas, con lo que tengas, donde estés.', 'Theodore Roosevelt'),
(6, 'El único modo de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs'),
(7, 'No se trata de tener ideas, sino de hacer que sucedan.', 'Scott Belsky'),
(8, 'Cree que puedes y ya estás a medio camino.', 'Theodore Roosevelt'),
(9, 'La disciplina es el puente entre metas y logros.', 'Jim Rohn'),
(10, 'Si buscas resultados distintos, no hagas siempre lo mismo.', 'Albert Einstein'),
(11, 'Nunca es demasiado tarde para ser quien podrías haber sido.', 'George Eliot'),
(12, 'Todo lo que puedas imaginar es real.', 'Pablo Picasso'),
(13, 'No mires el reloj; haz lo que él hace: sigue adelante.', 'Sam Levenson'),
(14, 'No hay atajos para alcanzar lugares que valen la pena.', 'Beverly Sills'),
(15, 'La motivación te impulsa a comenzar. El hábito te mantiene en marcha.', 'Jim Ryun'),
(16, 'Haz de cada día tu obra maestra.', 'John Wooden'),
(17, 'El futuro pertenece a quienes creen en la belleza de sus sueños.', 'Eleanor Roosevelt'),
(18, 'Nunca sueñes con el éxito. Trabaja para alcanzarlo.', 'Estee Lauder'),
(19, 'Cree en ti mismo y todo será posible.', 'Napoleon Hill'),
(20, 'La confianza en uno mismo es el primer secreto del éxito.', 'Ralph Waldo Emerson'),
(21, 'Hazlo con pasión o no lo hagas.', 'Rosa Nouchette Carey'),
(22, 'Actúa como si lo que hicieras marcara la diferencia. Lo hace.', 'William James'),
(23, 'La acción es la clave fundamental de todo éxito.', 'Pablo Picasso'),
(24, 'Persiste. Nada en el mundo puede sustituir la persistencia.', 'Calvin Coolidge'),
(25, 'El único límite a nuestros logros de mañana es nuestras dudas de hoy.', 'Franklin D. Roosevelt'),
(26, 'No esperes. El tiempo nunca será justo.', 'Napoleon Hill'),
(27, 'La única diferencia entre un buen día y un mal día es tu actitud.', 'Dennis S. Brown'),
(28, 'Cuanto más haces, más puedes hacer.', 'Lucille Ball'),
(29, 'El trabajo duro vence al talento cuando el talento no trabaja duro.', 'Tim Notke'),
(30, 'No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.', 'John D. Rockefeller'),
(31, 'El fracaso es una gran oportunidad para empezar otra vez con más inteligencia.', 'Henry Ford'),
(32, 'No te compares con nadie, compite contigo mismo.', 'William Faulkner'),
(33, 'El dolor es temporal. Renunciar es para siempre.', 'Lance Armstrong'),
(34, 'La motivación es lo que te pone en marcha. El hábito es lo que hace que sigas.', 'Jim Ryun'),
(35, 'Piensa en grande y no escuches a los que te dicen que no se puede.', 'Tim Ferriss'),
(36, 'A veces lo más productivo que puedes hacer es relajarte.', 'Mark Black'),
(37, 'Nunca te rindas. Hoy es difícil, mañana será peor, pero pasado mañana saldrá el sol.', 'Jack Ma'),
(38, 'El coraje no siempre ruge. A veces el coraje es la voz tranquila al final del día que dice: mañana lo volveré a intentar.', 'Mary Anne Radmacher'),
(39, 'La mejor forma de empezar es dejar de hablar y comenzar a hacer.', 'Walt Disney'),
(40, 'Si puedes soñarlo, puedes hacerlo.', 'Walt Disney'),
(41, 'La calidad no es un acto, es un hábito.', 'Aristóteles'),
(42, 'El éxito no es para los que piensan que pueden hacerlo, sino para los que lo hacen.', 'Anónimo'),
(43, 'Transforma tus heridas en sabiduría.', 'Oprah Winfrey'),
(44, 'Aprovecha cada momento porque cada segundo cuenta.', 'Marie Forleo'),
(45, 'El secreto para salir adelante es comenzar.', 'Mark Twain'),
(46, 'Nada es particularmente difícil si lo divides en pequeños trabajos.', 'Henry Ford'),
(47, 'La mejor preparación para mañana es hacer lo mejor hoy.', 'H. Jackson Brown Jr.'),
(48, 'Esfuerzo continuo, no fuerza o inteligencia, es la clave para liberar nuestro potencial.', 'Winston S. Churchill'),
(49, 'Nunca permitas que el miedo decida tu futuro.', 'Robin Sharma'),
(50, 'El cambio no es una amenaza, es una oportunidad.', 'Seth Godin'),
(51, 'Cree en ti mismo incluso cuando nadie más lo haga.', 'Sara Blakely'),
(52, 'La clave del éxito es empezar antes de estar listo.', 'Marie Forleo'),
(53, 'A veces ganarás, otras veces aprenderás.', 'John Maxwell'),
(54, 'Tu mayor recurso es tu tiempo.', 'Brian Tracy'),
(55, 'La constancia es lo que convierte lo ordinario en extraordinario.', 'Jimmy Johnson'),
(56, 'No tienes que ser grande para empezar, pero tienes que empezar para ser grande.', 'Zig Ziglar'),
(57, 'La actitud lo es todo.', 'Diane Von Furstenberg'),
(58, 'El trabajo duro hace que desaparezcan las arrugas del fracaso.', 'Sophia Loren'),
(59, 'Sueña en grande. Comienza en pequeño. Actúa ahora.', 'Robin Sharma'),
(60, 'No te detengas hasta estar orgulloso.', 'Anónimo'),
(61, 'Sé tú el cambio que deseas ver en el mundo.', 'Mahatma Gandhi'),
(62, 'Cambia tus pensamientos y cambiarás tu mundo.', 'Norman Vincent Peale'),
(63, 'La perseverancia no es una carrera larga; son muchas carreras cortas una tras otra.', 'Walter Elliot'),
(64, 'Hazlo o no lo hagas, pero no lo intentes.', 'Yoda'),
(65, 'Levántate con determinación. Acuéstate con satisfacción.', 'Anónimo'),
(66, 'El fracaso derrota a los perdedores e inspira a los ganadores.', 'Robert T. Kiyosaki'),
(67, 'Cuando todo parezca estar en tu contra, recuerda que el avión despega contra el viento.', 'Henry Ford'),
(68, 'No dejes que lo que no puedes hacer interfiera con lo que puedes hacer.', 'John Wooden'),
(69, 'La energía y la persistencia conquistan todas las cosas.', 'Benjamin Franklin'),
(70, 'Donde hay una voluntad, hay un camino.', 'Pauline Kael'),
(71, 'Si vas a dudar de algo, duda de tus límites.', 'Don Ward'),
(72, 'La diferencia entre ganar y perder es, a menudo, no rendirse.', 'Walt Disney'),
(73, 'Haz lo que amas y nunca trabajarás un solo día en tu vida.', 'Confucio'),
(74, 'Lo que no se empieza hoy nunca se termina mañana.', 'Johann Wolfgang von Goethe'),
(75, 'Las grandes obras son hechas no con fuerza, sino con perseverancia.', 'Samuel Johnson'),
(76, 'Apunta a la luna. Incluso si fallas, aterrizarás entre las estrellas.', 'Les Brown'),
(77, 'Sé tan bueno que no puedan ignorarte.', 'Steve Martin'),
(78, 'A veces, la caída te enseña a volar.', 'Anónimo'),
(79, 'Los límites sólo están en tu mente.', 'Anónimo'),
(80, 'Si puedes visualizarlo, puedes lograrlo.', 'Joel Osteen'),
(81, 'El éxito no se logra solo con cualidades especiales. Es sobre todo un trabajo de constancia.', 'Angela Duckworth'),
(82, 'La inspiración existe, pero tiene que encontrarte trabajando.', 'Pablo Picasso'),
(83, 'No sueñes tu vida, vive tu sueño.', 'Anónimo'),
(84, 'La única forma de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs'),
(85, 'Nadie que haya dado lo mejor de sí lo ha lamentado.', 'George Halas'),
(86, 'Empieza donde estás. Usa lo que tienes. Haz lo que puedas.', 'Arthur Ashe'),
(87, 'Tus sueños no tienen fecha de caducidad.', 'Anónimo'),
(88, 'Haz que cada día cuente.', 'Muhammad Ali'),
(89, 'El único lugar donde el éxito viene antes del trabajo es en el diccionario.', 'Vidal Sassoon'),
(90, 'Los grandes logros requieren grandes sacrificios.', 'James Allen'),
(91, 'Nunca es demasiado tarde para comenzar de nuevo.', 'Jack Kornfield'),
(92, 'Las oportunidades no pasan, las creas.', 'Chris Grosser'),
(93, 'Cree que puedes, y ya estás a mitad de camino.', 'Theodore Roosevelt'),
(94, 'La pasión es energía. Siente el poder que viene de centrarte en lo que te entusiasma.', 'Oprah Winfrey'),
(95, 'Haz lo que amas, ama lo que haces.', 'Ray Bradbury'),
(96, 'Lo que haces hoy puede mejorar todos tus mañanas.', 'Ralph Marston'),
(97, 'No es la carga lo que te rompe, sino la forma en que la llevas.', 'Lou Holtz'),
(98, 'Los desafíos hacen la vida interesante, superarlos la hace significativa.', 'Joshua Marine'),
(99, 'Nadie puede hacerte sentir inferior sin tu consentimiento.', 'Eleanor Roosevelt'),
(100, 'Todo lo que siempre has querido está al otro lado del miedo.', 'George Addair');