// seedQuotes.js
import Quote from '../models/Quotes.js';

const initialQuotes = [
    { id: 1, quote: 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', author: 'Robert Collier' },
    { id: 2, quote: 'La mejor manera de predecir el futuro es creándolo.', author: 'Peter Drucker' },
    { id: 3, quote: 'No cuentes los días, haz que los días cuenten.', author: 'Muhammad Ali' },
    { id: 4, quote: 'La vida es 10% lo que te ocurre y 90% cómo reaccionas a ello.', author: 'Charles R. Swindoll' },
    { id: 5, quote: 'Haz lo que puedas, con lo que tengas, donde estés.', author: 'Theodore Roosevelt' },
    { id: 6, quote: 'El único modo de hacer un gran trabajo es amar lo que haces.', author: 'Steve Jobs' },
    { id: 7, quote: 'No se trata de tener ideas, sino de hacer que sucedan.', author: 'Scott Belsky' },
    { id: 8, quote: 'Cree que puedes y ya estás a medio camino.', author: 'Theodore Roosevelt' },
    { id: 9, quote: 'La disciplina es el puente entre metas y logros.', author: 'Jim Rohn' },
    { id: 10, quote: 'Si buscas resultados distintos, no hagas siempre lo mismo.', author: 'Albert Einstein' },
    { id: 11, quote: 'Nunca es demasiado tarde para ser quien podrías haber sido.', author: 'George Eliot' },
    { id: 12, quote: 'Todo lo que puedas imaginar es real.', author: 'Pablo Picasso' },
    { id: 13, quote: 'No mires el reloj; haz lo que él hace: sigue adelante.', author: 'Sam Levenson' },
    { id: 14, quote: 'No hay atajos para alcanzar lugares que valen la pena.', author: 'Beverly Sills' },
    { id: 15, quote: 'La motivación te impulsa a comenzar. El hábito te mantiene en marcha.', author: 'Jim Ryun' },
    { id: 16, quote: 'Haz de cada día tu obra maestra.', author: 'John Wooden' },
    { id: 17, quote: 'El futuro pertenece a quienes creen en la belleza de sus sueños.', author: 'Eleanor Roosevelt' },
    { id: 18, quote: 'Nunca sueñes con el éxito. Trabaja para alcanzarlo.', author: 'Estee Lauder' },
    { id: 19, quote: 'Cree en ti mismo y todo será posible.', author: 'Napoleon Hill' },
    { id: 20, quote: 'La confianza en uno mismo es el primer secreto del éxito.', author: 'Ralph Waldo Emerson' },
    { id: 21, quote: 'Hazlo con pasión o no lo hagas.', author: 'Rosa Nouchette Carey' },
    { id: 22, quote: 'Actúa como si lo que hicieras marcara la diferencia. Lo hace.', author: 'William James' },
    { id: 23, quote: 'La acción es la clave fundamental de todo éxito.', author: 'Pablo Picasso' },
    { id: 24, quote: 'Persiste. Nada en el mundo puede sustituir la persistencia.', author: 'Calvin Coolidge' },
    { id: 25, quote: 'El único límite a nuestros logros de mañana es nuestras dudas de hoy.', author: 'Franklin D. Roosevelt' },
    { id: 26, quote: 'No esperes. El tiempo nunca será justo.', author: 'Napoleon Hill' },
    { id: 27, quote: 'La única diferencia entre un buen día y un mal día es tu actitud.', author: 'Dennis S. Brown' },
    { id: 28, quote: 'Cuanto más haces, más puedes hacer.', author: 'Lucille Ball' },
    { id: 29, quote: 'El trabajo duro vence al talento cuando el talento no trabaja duro.', author: 'Tim Notke' },
    { id: 30, quote: 'No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.', author: 'John D. Rockefeller' },
    { id: 31, quote: 'El fracaso es una gran oportunidad para empezar otra vez con más inteligencia.', author: 'Henry Ford' },
    { id: 32, quote: 'No te compares con nadie, compite contigo mismo.', author: 'William Faulkner' },
    { id: 33, quote: 'El dolor es temporal. Renunciar es para siempre.', author: 'Lance Armstrong' },
    { id: 34, quote: 'La motivación es lo que te pone en marcha. El hábito es lo que hace que sigas.', author: 'Jim Ryun' },
    { id: 35, quote: 'Piensa en grande y no escuches a los que te dicen que no se puede.', author: 'Tim Ferriss' },
    { id: 36, quote: 'A veces lo más productivo que puedes hacer es relajarte.', author: 'Mark Black' },
    { id: 37, quote: 'Nunca te rindas. Hoy es difícil, mañana será peor, pero pasado mañana saldrá el sol.', author: 'Jack Ma' },
    { id: 38, quote: 'El coraje no siempre ruge. A veces el coraje es la voz tranquila al final del día que dice: mañana lo volveré a intentar.', author: 'Mary Anne Radmacher' },
    { id: 39, quote: 'La mejor forma de empezar es dejar de hablar y comenzar a hacer.', author: 'Walt Disney' },
    { id: 40, quote: 'Si puedes soñarlo, puedes hacerlo.', author: 'Walt Disney' },
    { id: 41, quote: 'La calidad no es un acto, es un hábito.', author: 'Aristóteles' },
    { id: 42, quote: 'El éxito no es para los que piensan que pueden hacerlo, sino para los que lo hacen.', author: 'Anónimo' },
    { id: 43, quote: 'Transforma tus heridas en sabiduría.', author: 'Oprah Winfrey' },
    { id: 44, quote: 'Aprovecha cada momento porque cada segundo cuenta.', author: 'Marie Forleo' },
    { id: 45, quote: 'El secreto para salir adelante es comenzar.', author: 'Mark Twain' },
    { id: 46, quote: 'Nada es particularmente difícil si lo divides en pequeños trabajos.', author: 'Henry Ford' },
    { id: 47, quote: 'La mejor preparación para mañana es hacer lo mejor hoy.', author: 'H. Jackson Brown Jr.' },
    { id: 48, quote: 'Esfuerzo continuo, no fuerza o inteligencia, es la clave para liberar nuestro potencial.', author: 'Winston S. Churchill' },
    { id: 49, quote: 'Nunca permitas que el miedo decida tu futuro.', author: 'Robin Sharma' },
    { id: 50, quote: 'El cambio no es una amenaza, es una oportunidad.', author: 'Seth Godin' },
    { id: 51, quote: 'Cree en ti mismo incluso cuando nadie más lo haga.', author: 'Sara Blakely' },
    { id: 52, quote: 'La clave del éxito es empezar antes de estar listo.', author: 'Marie Forleo' },
    { id: 53, quote: 'A veces ganarás, otras veces aprenderás.', author: 'John Maxwell' },
    { id: 54, quote: 'Tu mayor recurso es tu tiempo.', author: 'Brian Tracy' },
    { id: 55, quote: 'La constancia es lo que convierte lo ordinario en extraordinario.', author: 'Jimmy Johnson' },
    { id: 56, quote: 'No tienes que ser grande para empezar, pero tienes que empezar para ser grande.', author: 'Zig Ziglar' },
    { id: 57, quote: 'La actitud lo es todo.', author: 'Diane Von Furstenberg' },
    { id: 58, quote: 'El trabajo duro hace que desaparezcan las arrugas del fracaso.', author: 'Sophia Loren' },
    { id: 59, quote: 'Sueña en grande. Comienza en pequeño. Actúa ahora.', author: 'Robin Sharma' },
    { id: 60, quote: 'No te detengas hasta estar orgulloso.', author: 'Anónimo' },
    { id: 61, quote: 'Sé tú el cambio que deseas ver en el mundo.', author: 'Mahatma Gandhi' },
    { id: 62, quote: 'Cambia tus pensamientos y cambiarás tu mundo.', author: 'Norman Vincent Peale' },
    { id: 63, quote: 'La perseverancia no es una carrera larga; son muchas carreras cortas una tras otra.', author: 'Walter Elliot' },
    { id: 64, quote: 'Hazlo o no lo hagas, pero no lo intentes.', author: 'Yoda' },
    { id: 65, quote: 'Levántate con determinación. Acuéstate con satisfacción.', author: 'Anónimo' },
    { id: 66, quote: 'El fracaso derrota a los perdedores e inspira a los ganadores.', author: 'Robert T. Kiyosaki' },
    { id: 67, quote: 'Cuando todo parezca estar en tu contra, recuerda que el avión despega contra el viento.', author: 'Henry Ford' },
    { id: 68, quote: 'No dejes que lo que no puedes hacer interfiera con lo que puedes hacer.', author: 'John Wooden' },
    { id: 69, quote: 'La energía y la persistencia conquistan todas las cosas.', author: 'Benjamin Franklin' },
    { id: 70, quote: 'Donde hay una voluntad, hay un camino.', author: 'Pauline Kael' },
    { id: 71, quote: 'Si vas a dudar de algo, duda de tus límites.', author: 'Don Ward' },
    { id: 72, quote: 'La diferencia entre ganar y perder es, a menudo, no rendirse.', author: 'Walt Disney' },
    { id: 73, quote: 'Haz lo que amas y nunca trabajarás un solo día en tu vida.', author: 'Confucio' },
    { id: 74, quote: 'Lo que no se empieza hoy nunca se termina mañana.', author: 'Johann Wolfgang von Goethe' },
    { id: 75, quote: 'Las grandes obras son hechas no con fuerza, sino con perseverancia.', author: 'Samuel Johnson' },
    { id: 76, quote: 'Apunta a la luna. Incluso si fallas, aterrizarás entre las estrellas.', author: 'Les Brown' },
    { id: 77, quote: 'Sé tan bueno que no puedan ignorarte.', author: 'Steve Martin' },
    { id: 78, quote: 'A veces, la caída te enseña a volar.', author: 'Anónimo' },
    { id: 79, quote: 'Los límites sólo están en tu mente.', author: 'Anónimo' },
    { id: 80, quote: 'Si puedes visualizarlo, puedes lograrlo.', author: 'Joel Osteen' },
    { id: 81, quote: 'El éxito no se logra solo con cualidades especiales. Es sobre todo un trabajo de constancia.', author: 'Angela Duckworth' },
    { id: 82, quote: 'La inspiración existe, pero tiene que encontrarte trabajando.', author: 'Pablo Picasso' },
    { id: 83, quote: 'No sueñes tu vida, vive tu sueño.', author: 'Anónimo' },
    { id: 84, quote: 'La única forma de hacer un gran trabajo es amar lo que haces.', author: 'Steve Jobs' },
    { id: 85, quote: 'Nadie que haya dado lo mejor de sí lo ha lamentado.', author: 'George Halas' },
    { id: 86, quote: 'Empieza donde estás. Usa lo que tienes. Haz lo que puedas.', author: 'Arthur Ashe' },
    { id: 87, quote: 'Tus sueños no tienen fecha de caducidad.', author: 'Anónimo' },
    { id: 88, quote: 'Haz que cada día cuente.', author: 'Muhammad Ali' },
    { id: 89, quote: 'El único lugar donde el éxito viene antes del trabajo es en el diccionario.', author: 'Vidal Sassoon' },
    { id: 90, quote: 'Los grandes logros requieren grandes sacrificios.', author: 'James Allen' },
    { id: 91, quote: 'Nunca es demasiado tarde para comenzar de nuevo.', author: 'Jack Kornfield' },
    { id: 92, quote: 'Las oportunidades no pasan, las creas.', author: 'Chris Grosser' },
    { id: 93, quote: 'Cree que puedes, y ya estás a mitad de camino.', author: 'Theodore Roosevelt' },
    { id: 94, quote: 'La pasión es energía. Siente el poder que viene de centrarte en lo que te entusiasma.', author: 'Oprah Winfrey' },
    { id: 95, quote: 'Haz lo que amas, ama lo que haces.', author: 'Ray Bradbury' },
    { id: 96, quote: 'Lo que haces hoy puede mejorar todos tus mañanas.', author: 'Ralph Marston' },
    { id: 97, quote: 'No es la carga lo que te rompe, sino la forma en que la llevas.', author: 'Lou Holtz' },
    { id: 98, quote: 'Los desafíos hacen la vida interesante, superarlos la hace significativa.', author: 'Joshua Marine' },
    { id: 99, quote: 'Nadie puede hacerte sentir inferior sin tu consentimiento.', author: 'Eleanor Roosevelt' },
    { id: 100, quote: 'Todo lo que siempre has querido está al otro lado del miedo.', author: 'George Addair' },
    { id: 101, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Tomás Ruiz' },
    { id: 102, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'María Luna' },
    { id: 103, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Mateo Vargas' },
    { id: 104, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Emilia Suárez' },
    { id: 105, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Julián Torres' },
    { id: 106, quote: 'Los límites existen solo para ser desafiados.', author: 'Sofía Delgado' },
    { id: 107, quote: 'No es magia, es constancia.', author: 'Nicolás Cabrera' },
    { id: 108, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Bruno Castaño' },
    { id: 109, quote: 'El primer intento es el inicio de lo posible.', author: 'Clara Méndez' },
    { id: 110, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Isabel Navarro' },
    { id: 111, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Sebastián Molina' },
    { id: 112, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Andrés Salazar' },
    { id: 113, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'María Luna' },
    { id: 114, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'María Luna' },
    { id: 115, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Andrés Salazar' },
    { id: 116, quote: 'Los límites existen solo para ser desafiados.', author: 'Iván Romero' },
    { id: 117, quote: 'No es magia, es constancia.', author: 'Elena Figueroa' },
    { id: 118, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Nicolás Cabrera' },
    { id: 119, quote: 'El primer intento es el inicio de lo posible.', author: 'Sebastián Molina' },
    { id: 120, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Nicolás Cabrera' },
    { id: 121, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Mateo Vargas' },
    { id: 122, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Valentina Paredes' },
    { id: 123, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Nicolás Cabrera' },
    { id: 124, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Diego Castellanos' },
    { id: 125, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Sofía Delgado' },
    { id: 126, quote: 'Los límites existen solo para ser desafiados.', author: 'Mateo Vargas' },
    { id: 127, quote: 'No es magia, es constancia.', author: 'Elena Figueroa' },
    { id: 128, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Camila Ortega' },
    { id: 129, quote: 'El primer intento es el inicio de lo posible.', author: 'Isabel Navarro' },
    { id: 130, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Emilia Suárez' },
    { id: 131, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Renata Zamora' },
    { id: 132, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'María Luna' },
    { id: 133, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Bruno Castaño' },
    { id: 134, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Andrés Salazar' },
    { id: 135, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Bruno Castaño' },
    { id: 136, quote: 'Los límites existen solo para ser desafiados.', author: 'Elena Figueroa' },
    { id: 137, quote: 'No es magia, es constancia.', author: 'Valentina Paredes' },
    { id: 138, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Sebastián Molina' },
    { id: 139, quote: 'El primer intento es el inicio de lo posible.', author: 'Sofía Delgado' },
    { id: 140, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Nicolás Cabrera' },
    { id: 141, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'María Luna' },
    { id: 142, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Nicolás Cabrera' },
    { id: 143, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Elena Figueroa' },
    { id: 144, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Elena Figueroa' },
    { id: 145, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Emilia Suárez' },
    { id: 146, quote: 'Los límites existen solo para ser desafiados.', author: 'María Luna' },
    { id: 147, quote: 'No es magia, es constancia.', author: 'Nicolás Cabrera' },
    { id: 148, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Sofía Delgado' },
    { id: 149, quote: 'El primer intento es el inicio de lo posible.', author: 'Sofía Delgado' },
    { id: 150, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Tomás Ruiz' },
    { id: 151, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Tomás Ruiz' },
    { id: 152, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Lucía Herrera' },
    { id: 153, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Elena Figueroa' },
    { id: 154, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Sebastián Molina' },
    { id: 155, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Elena Figueroa' },
    { id: 156, quote: 'Los límites existen solo para ser desafiados.', author: 'Renata Zamora' },
    { id: 157, quote: 'No es magia, es constancia.', author: 'Andrés Salazar' },
    { id: 158, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Sofía Delgado' },
    { id: 159, quote: 'El primer intento es el inicio de lo posible.', author: 'Iván Romero' },
    { id: 160, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Iván Romero' },
    { id: 161, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Clara Méndez' },
    { id: 162, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Clara Méndez' },
    { id: 163, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Tomás Ruiz' },
    { id: 164, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'María Luna' },
    { id: 165, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Renata Zamora' },
    { id: 166, quote: 'Los límites existen solo para ser desafiados.', author: 'Andrés Salazar' },
    { id: 167, quote: 'No es magia, es constancia.', author: 'Camila Ortega' },
    { id: 168, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'María Luna' },
    { id: 169, quote: 'El primer intento es el inicio de lo posible.', author: 'Clara Méndez' },
    { id: 170, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Bruno Castaño' },
    { id: 171, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Tomás Ruiz' },
    { id: 172, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Camila Ortega' },
    { id: 173, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Nicolás Cabrera' },
    { id: 174, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Valentina Paredes' },
    { id: 175, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Sofía Delgado' },
    { id: 176, quote: 'Los límites existen solo para ser desafiados.', author: 'Diego Castellanos' },
    { id: 177, quote: 'No es magia, es constancia.', author: 'Mateo Vargas' },
    { id: 178, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Elena Figueroa' },
    { id: 179, quote: 'El primer intento es el inicio de lo posible.', author: 'Julián Torres' },
    { id: 180, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Sofía Delgado' },
    { id: 181, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Isabel Navarro' },
    { id: 182, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Julián Torres' },
    { id: 183, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Mateo Vargas' },
    { id: 184, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Gabriel Rojas' },
    { id: 185, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Mateo Vargas' },
    { id: 186, quote: 'Los límites existen solo para ser desafiados.', author: 'Clara Méndez' },
    { id: 187, quote: 'No es magia, es constancia.', author: 'Sofía Delgado' },
    { id: 188, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Isabel Navarro' },
    { id: 189, quote: 'El primer intento es el inicio de lo posible.', author: 'María Luna' },
    { id: 190, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Clara Méndez' },
    { id: 191, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Tomás Ruiz' },
    { id: 192, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Lucía Herrera' },
    { id: 193, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'María Luna' },
    { id: 194, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'María Luna' },
    { id: 195, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Andrés Salazar' },
    { id: 196, quote: 'Los límites existen solo para ser desafiados.', author: 'Gabriel Rojas' },
    { id: 197, quote: 'No es magia, es constancia.', author: 'Sofía Delgado' },
    { id: 198, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Andrés Salazar' },
    { id: 199, quote: 'El primer intento es el inicio de lo posible.', author: 'Clara Méndez' },
    { id: 200, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Diego Castellanos' },
    { id: 201, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Valentina Paredes' },
    { id: 202, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Nicolás Cabrera' },
    { id: 203, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Diego Castellanos' },
    { id: 204, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Bruno Castaño' },
    { id: 205, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Sofía Delgado' },
    { id: 206, quote: 'Los límites existen solo para ser desafiados.', author: 'Julián Torres' },
    { id: 207, quote: 'No es magia, es constancia.', author: 'Valentina Paredes' },
    { id: 208, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Mateo Vargas' },
    { id: 209, quote: 'El primer intento es el inicio de lo posible.', author: 'Diego Castellanos' },
    { id: 210, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Renata Zamora' },
    { id: 211, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'María Luna' },
    { id: 212, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Andrés Salazar' },
    { id: 213, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Camila Ortega' },
    { id: 214, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Sebastián Molina' },
    { id: 215, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Julián Torres' },
    { id: 216, quote: 'Los límites existen solo para ser desafiados.', author: 'Nicolás Cabrera' },
    { id: 217, quote: 'No es magia, es constancia.', author: 'Julián Torres' },
    { id: 218, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Mateo Vargas' },
    { id: 219, quote: 'El primer intento es el inicio de lo posible.', author: 'Isabel Navarro' },
    { id: 220, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Iván Romero' },
    { id: 221, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'María Luna' },
    { id: 222, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Renata Zamora' },
    { id: 223, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Emilia Suárez' },
    { id: 224, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Elena Figueroa' },
    { id: 225, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Iván Romero' },
    { id: 226, quote: 'Los límites existen solo para ser desafiados.', author: 'Tomás Ruiz' },
    { id: 227, quote: 'No es magia, es constancia.', author: 'Emilia Suárez' },
    { id: 228, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Andrés Salazar' },
    { id: 229, quote: 'El primer intento es el inicio de lo posible.', author: 'Isabel Navarro' },
    { id: 230, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Bruno Castaño' },
    { id: 231, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Camila Ortega' },
    { id: 232, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Camila Ortega' },
    { id: 233, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Tomás Ruiz' },
    { id: 234, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Lucía Herrera' },
    { id: 235, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Isabel Navarro' },
    { id: 236, quote: 'Los límites existen solo para ser desafiados.', author: 'Mateo Vargas' },
    { id: 237, quote: 'No es magia, es constancia.', author: 'Renata Zamora' },
    { id: 238, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Lucía Herrera' },
    { id: 239, quote: 'El primer intento es el inicio de lo posible.', author: 'Valentina Paredes' },
    { id: 240, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Lucía Herrera' },
    { id: 241, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Renata Zamora' },
    { id: 242, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Emilia Suárez' },
    { id: 243, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Clara Méndez' },
    { id: 244, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Julián Torres' },
    { id: 245, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Camila Ortega' },
    { id: 246, quote: 'Los límites existen solo para ser desafiados.', author: 'Renata Zamora' },
    { id: 247, quote: 'No es magia, es constancia.', author: 'Diego Castellanos' },
    { id: 248, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Julián Torres' },
    { id: 249, quote: 'El primer intento es el inicio de lo posible.', author: 'Isabel Navarro' },
    { id: 250, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Julián Torres' },
    { id: 251, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Nicolás Cabrera' },
    { id: 252, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Clara Méndez' },
    { id: 253, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Sofía Delgado' },
    { id: 254, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Renata Zamora' },
    { id: 255, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Valentina Paredes' },
    { id: 256, quote: 'Los límites existen solo para ser desafiados.', author: 'María Luna' },
    { id: 257, quote: 'No es magia, es constancia.', author: 'Camila Ortega' },
    { id: 258, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Sebastián Molina' },
    { id: 259, quote: 'El primer intento es el inicio de lo posible.', author: 'Mateo Vargas' },
    { id: 260, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'María Luna' },
    { id: 261, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Gabriel Rojas' },
    { id: 262, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Clara Méndez' },
    { id: 263, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Nicolás Cabrera' },
    { id: 264, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'María Luna' },
    { id: 265, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Valentina Paredes' },
    { id: 266, quote: 'Los límites existen solo para ser desafiados.', author: 'Renata Zamora' },
    { id: 267, quote: 'No es magia, es constancia.', author: 'Sebastián Molina' },
    { id: 268, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Gabriel Rojas' },
    { id: 269, quote: 'El primer intento es el inicio de lo posible.', author: 'Julián Torres' },
    { id: 270, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Gabriel Rojas' },
    { id: 271, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Elena Figueroa' },
    { id: 272, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Iván Romero' },
    { id: 273, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Tomás Ruiz' },
    { id: 274, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Elena Figueroa' },
    { id: 275, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Camila Ortega' },
    { id: 276, quote: 'Los límites existen solo para ser desafiados.', author: 'Bruno Castaño' },
    { id: 277, quote: 'No es magia, es constancia.', author: 'Isabel Navarro' },
    { id: 278, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'María Luna' },
    { id: 279, quote: 'El primer intento es el inicio de lo posible.', author: 'Elena Figueroa' },
    { id: 280, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Sofía Delgado' },
    { id: 281, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Lucía Herrera' },
    { id: 282, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Tomás Ruiz' },
    { id: 283, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Camila Ortega' },
    { id: 284, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Iván Romero' },
    { id: 285, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Nicolás Cabrera' },
    { id: 286, quote: 'Los límites existen solo para ser desafiados.', author: 'Sofía Delgado' },
    { id: 287, quote: 'No es magia, es constancia.', author: 'Valentina Paredes' },
    { id: 288, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Tomás Ruiz' },
    { id: 289, quote: 'El primer intento es el inicio de lo posible.', author: 'Nicolás Cabrera' },
    { id: 290, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Renata Zamora' },
    { id: 291, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Julián Torres' },
    { id: 292, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Camila Ortega' },
    { id: 293, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Andrés Salazar' },
    { id: 294, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Iván Romero' },
    { id: 295, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Sofía Delgado' },
    { id: 296, quote: 'Los límites existen solo para ser desafiados.', author: 'Valentina Paredes' },
    { id: 297, quote: 'No es magia, es constancia.', author: 'Valentina Paredes' },
    { id: 298, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Mateo Vargas' },
    { id: 299, quote: 'El primer intento es el inicio de lo posible.', author: 'Gabriel Rojas' },
    { id: 300, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Renata Zamora' },
    { id: 301, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Mateo Vargas' },
    { id: 302, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Julián Torres' },
    { id: 303, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Emilia Suárez' },
    { id: 304, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Sebastián Molina' },
    { id: 305, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Renata Zamora' },
    { id: 306, quote: 'Los límites existen solo para ser desafiados.', author: 'Sebastián Molina' },
    { id: 307, quote: 'No es magia, es constancia.', author: 'Tomás Ruiz' },
    { id: 308, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Tomás Ruiz' },
    { id: 309, quote: 'El primer intento es el inicio de lo posible.', author: 'Renata Zamora' },
    { id: 310, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Isabel Navarro' },
    { id: 311, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Sofía Delgado' },
    { id: 312, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Diego Castellanos' },
    { id: 313, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Julián Torres' },
    { id: 314, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'María Luna' },
    { id: 315, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Tomás Ruiz' },
    { id: 316, quote: 'Los límites existen solo para ser desafiados.', author: 'Elena Figueroa' },
    { id: 317, quote: 'No es magia, es constancia.', author: 'Isabel Navarro' },
    { id: 318, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Lucía Herrera' },
    { id: 319, quote: 'El primer intento es el inicio de lo posible.', author: 'Julián Torres' },
    { id: 320, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Iván Romero' },
    { id: 321, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Emilia Suárez' },
    { id: 322, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Isabel Navarro' },
    { id: 323, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Lucía Herrera' },
    { id: 324, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Clara Méndez' },
    { id: 325, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Gabriel Rojas' },
    { id: 326, quote: 'Los límites existen solo para ser desafiados.', author: 'Mateo Vargas' },
    { id: 327, quote: 'No es magia, es constancia.', author: 'Mateo Vargas' },
    { id: 328, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Julián Torres' },
    { id: 329, quote: 'El primer intento es el inicio de lo posible.', author: 'Andrés Salazar' },
    { id: 330, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Sofía Delgado' },
    { id: 331, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Camila Ortega' },
    { id: 332, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Sofía Delgado' },
    { id: 333, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Mateo Vargas' },
    { id: 334, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Tomás Ruiz' },
    { id: 335, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Elena Figueroa' },
    { id: 336, quote: 'Los límites existen solo para ser desafiados.', author: 'Emilia Suárez' },
    { id: 337, quote: 'No es magia, es constancia.', author: 'Julián Torres' },
    { id: 338, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Nicolás Cabrera' },
    { id: 339, quote: 'El primer intento es el inicio de lo posible.', author: 'Sebastián Molina' },
    { id: 340, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Nicolás Cabrera' },
    { id: 341, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'María Luna' },
    { id: 342, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Renata Zamora' },
    { id: 343, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Mateo Vargas' },
    { id: 344, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Mateo Vargas' },
    { id: 345, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Bruno Castaño' },
    { id: 346, quote: 'Los límites existen solo para ser desafiados.', author: 'Andrés Salazar' },
    { id: 347, quote: 'No es magia, es constancia.', author: 'Lucía Herrera' },
    { id: 348, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Gabriel Rojas' },
    { id: 349, quote: 'El primer intento es el inicio de lo posible.', author: 'Nicolás Cabrera' },
    { id: 350, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Iván Romero' },
    { id: 351, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Clara Méndez' },
    { id: 352, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Iván Romero' },
    { id: 353, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Elena Figueroa' },
    { id: 354, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Valentina Paredes' },
    { id: 355, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Andrés Salazar' },
    { id: 356, quote: 'Los límites existen solo para ser desafiados.', author: 'Mateo Vargas' },
    { id: 357, quote: 'No es magia, es constancia.', author: 'Sebastián Molina' },
    { id: 358, quote: 'El esfuerzo constante vence al talento que descansa.', author: 'Iván Romero' },
    { id: 359, quote: 'El primer intento es el inicio de lo posible.', author: 'Julián Torres' },
    { id: 360, quote: 'Confía en el proceso, incluso cuando no veas resultados inmediatos.', author: 'Nicolás Cabrera' },
    { id: 361, quote: 'La perseverancia abre caminos donde antes solo había muros.', author: 'Isabel Navarro' },
    { id: 362, quote: 'Cada paso hacia adelante, por pequeño que sea, te aleja del ayer.', author: 'Mateo Vargas' },
    { id: 363, quote: 'Los sueños grandes comienzan con decisiones pequeñas.', author: 'Renata Zamora' },
    { id: 364, quote: 'El progreso no se mide en velocidad, sino en dirección.', author: 'Renata Zamora' },
    { id: 365, quote: 'El valor verdadero se revela cuando decides continuar.', author: 'Nicolás Cabrera' },
    { id: 366, quote: 'Cada día extra es una nueva oportunidad para crecer.', author: 'Lorena Cáceres' }
];

export default async function seedQuotesIfEmpty() {
    try {
        await Quote.destroy({ where: {} });
        await Quote.bulkCreate(initialQuotes);
        console.log('Frases insertadas correctamente');
    } catch (err) {
        console.error('Error al insertar frases:', err);
    }
}
