// seedQuotes.js
import Quote from '../models/Quotes.js';

const initialQuotes = [
    { id: 1, quote: 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', author: 'Robert Collier' },
    { id: 2, quote: 'La mejor manera de predecir el futuro es creándolo.', author: 'Peter Drucker' },
    { id: 3, quote: 'No cuentes los días, haz que los días cuenten.', author: 'Muhammad Ali' },
    { id: 4, quote: 'La vida es 10% lo que te ocurre y 90% cómo reaccionas a ello.', author: 'Charles R. Swindoll' },
    { id: 5, quote: 'Haz lo que puedas, con lo que tengas, donde estés.', author: 'Theodore Roosevelt' },
    { id: 6, quote: 'El único modo de hacer un gran trabajo es amar lo que haces.', author: 'Steve Jobs' },
    { id: 7, quote: 'No se trata de tener ideas, sino de hacer que sucedan.', author: 'Scott Belsky' },
    { id: 8, quote: 'Cree que puedes y ya estás a medio camino.', author: 'Theodore Roosevelt' },
    { id: 9, quote: 'La disciplina es el puente entre metas y logros.', author: 'Jim Rohn' },
    { id: 10, quote: 'Si buscas resultados distintos, no hagas siempre lo mismo.', author: 'Albert Einstein' },
    { id: 11, quote: 'Nunca es demasiado tarde para ser quien podrías haber sido.', author: 'George Eliot' },
    { id: 12, quote: 'Todo lo que puedas imaginar es real.', author: 'Pablo Picasso' },
    { id: 13, quote: 'No mires el reloj; haz lo que él hace: sigue adelante.', author: 'Sam Levenson' },
    { id: 14, quote: 'No hay atajos para alcanzar lugares que valen la pena.', author: 'Beverly Sills' },
    { id: 15, quote: 'La motivación te impulsa a comenzar. El hábito te mantiene en marcha.', author: 'Jim Ryun' },
    { id: 16, quote: 'Haz de cada día tu obra maestra.', author: 'John Wooden' },
    { id: 17, quote: 'El futuro pertenece a quienes creen en la belleza de sus sueños.', author: 'Eleanor Roosevelt' },
    { id: 18, quote: 'Nunca sueñes con el éxito. Trabaja para alcanzarlo.', author: 'Estee Lauder' },
    { id: 19, quote: 'Cree en ti mismo y todo será posible.', author: 'Napoleon Hill' },
    { id: 20, quote: 'La confianza en uno mismo es el primer secreto del éxito.', author: 'Ralph Waldo Emerson' },
    { id: 21, quote: 'Hazlo con pasión o no lo hagas.', author: 'Rosa Nouchette Carey' },
    { id: 22, quote: 'Actúa como si lo que hicieras marcara la diferencia. Lo hace.', author: 'William James' },
    { id: 23, quote: 'La acción es la clave fundamental de todo éxito.', author: 'Pablo Picasso' },
    { id: 24, quote: 'Persiste. Nada en el mundo puede sustituir la persistencia.', author: 'Calvin Coolidge' },
    { id: 25, quote: 'El único límite a nuestros logros de mañana es nuestras dudas de hoy.', author: 'Franklin D. Roosevelt' },
    { id: 26, quote: 'No esperes. El tiempo nunca será justo.', author: 'Napoleon Hill' },
    { id: 27, quote: 'La única diferencia entre un buen día y un mal día es tu actitud.', author: 'Dennis S. Brown' },
    { id: 28, quote: 'Cuanto más haces, más puedes hacer.', author: 'Lucille Ball' },
    { id: 29, quote: 'El trabajo duro vence al talento cuando el talento no trabaja duro.', author: 'Tim Notke' },
    { id: 30, quote: 'No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.', author: 'John D. Rockefeller' },
    { id: 31, quote: 'El fracaso es una gran oportunidad para empezar otra vez con más inteligencia.', author: 'Henry Ford' },
    { id: 32, quote: 'No te compares con nadie, compite contigo mismo.', author: 'William Faulkner' },
    { id: 33, quote: 'El dolor es temporal. Renunciar es para siempre.', author: 'Lance Armstrong' },
    { id: 34, quote: 'La motivación es lo que te pone en marcha. El hábito es lo que hace que sigas.', author: 'Jim Ryun' },
    { id: 35, quote: 'Piensa en grande y no escuches a los que te dicen que no se puede.', author: 'Tim Ferriss' },
    { id: 36, quote: 'A veces lo más productivo que puedes hacer es relajarte.', author: 'Mark Black' },
    { id: 37, quote: 'Nunca te rindas. Hoy es difícil, mañana será peor, pero pasado mañana saldrá el sol.', author: 'Jack Ma' },
    { id: 38, quote: 'El coraje no siempre ruge. A veces el coraje es la voz tranquila al final del día que dice: mañana lo volveré a intentar.', author: 'Mary Anne Radmacher' },
    { id: 39, quote: 'La mejor forma de empezar es dejar de hablar y comenzar a hacer.', author: 'Walt Disney' },
    { id: 40, quote: 'Si puedes soñarlo, puedes hacerlo.', author: 'Walt Disney' },
    { id: 41, quote: 'La calidad no es un acto, es un hábito.', author: 'Aristóteles' },
    { id: 42, quote: 'El éxito no es para los que piensan que pueden hacerlo, sino para los que lo hacen.', author: 'Anónimo' },
    { id: 43, quote: 'Transforma tus heridas en sabiduría.', author: 'Oprah Winfrey' },
    { id: 44, quote: 'Aprovecha cada momento porque cada segundo cuenta.', author: 'Marie Forleo' },
    { id: 45, quote: 'El secreto para salir adelante es comenzar.', author: 'Mark Twain' },
    { id: 46, quote: 'Nada es particularmente difícil si lo divides en pequeños trabajos.', author: 'Henry Ford' },
    { id: 47, quote: 'La mejor preparación para mañana es hacer lo mejor hoy.', author: 'H. Jackson Brown Jr.' },
    { id: 48, quote: 'Esfuerzo continuo, no fuerza o inteligencia, es la clave para liberar nuestro potencial.', author: 'Winston S. Churchill' },
    { id: 49, quote: 'Nunca permitas que el miedo decida tu futuro.', author: 'Robin Sharma' },
    { id: 50, quote: 'El cambio no es una amenaza, es una oportunidad.', author: 'Seth Godin' },
    { id: 51, quote: 'Cree en ti mismo incluso cuando nadie más lo haga.', author: 'Sara Blakely' },
    { id: 52, quote: 'La clave del éxito es empezar antes de estar listo.', author: 'Marie Forleo' },
    { id: 53, quote: 'A veces ganarás, otras veces aprenderás.', author: 'John Maxwell' },
    { id: 54, quote: 'Tu mayor recurso es tu tiempo.', author: 'Brian Tracy' },
    { id: 55, quote: 'La constancia es lo que convierte lo ordinario en extraordinario.', author: 'Jimmy Johnson' },
    { id: 56, quote: 'No tienes que ser grande para empezar, pero tienes que empezar para ser grande.', author: 'Zig Ziglar' },
    { id: 57, quote: 'La actitud lo es todo.', author: 'Diane Von Furstenberg' },
    { id: 58, quote: 'El trabajo duro hace que desaparezcan las arrugas del fracaso.', author: 'Sophia Loren' },
    { id: 59, quote: 'Sueña en grande. Comienza en pequeño. Actúa ahora.', author: 'Robin Sharma' },
    { id: 60, quote: 'No te detengas hasta estar orgulloso.', author: 'Anónimo' },
    { id: 61, quote: 'Sé tú el cambio que deseas ver en el mundo.', author: 'Mahatma Gandhi' },
    { id: 62, quote: 'Cambia tus pensamientos y cambiarás tu mundo.', author: 'Norman Vincent Peale' },
    { id: 63, quote: 'La perseverancia no es una carrera larga; son muchas carreras cortas una tras otra.', author: 'Walter Elliot' },
    { id: 64, quote: 'Hazlo o no lo hagas, pero no lo intentes.', author: 'Yoda' },
    { id: 65, quote: 'Levántate con determinación. Acuéstate con satisfacción.', author: 'Anónimo' },
    { id: 66, quote: 'El fracaso derrota a los perdedores e inspira a los ganadores.', author: 'Robert T. Kiyosaki' },
    { id: 67, quote: 'Cuando todo parezca estar en tu contra, recuerda que el avión despega contra el viento.', author: 'Henry Ford' },
    { id: 68, quote: 'No dejes que lo que no puedes hacer interfiera con lo que puedes hacer.', author: 'John Wooden' },
    { id: 69, quote: 'La energía y la persistencia conquistan todas las cosas.', author: 'Benjamin Franklin' },
    { id: 70, quote: 'Donde hay una voluntad, hay un camino.', author: 'Pauline Kael' },
    { id: 71, quote: 'Si vas a dudar de algo, duda de tus límites.', author: 'Don Ward' },
    { id: 72, quote: 'La diferencia entre ganar y perder es, a menudo, no rendirse.', author: 'Walt Disney' },
    { id: 73, quote: 'Haz lo que amas y nunca trabajarás un solo día en tu vida.', author: 'Confucio' },
    { id: 74, quote: 'Lo que no se empieza hoy nunca se termina mañana.', author: 'Johann Wolfgang von Goethe' },
    { id: 75, quote: 'Las grandes obras son hechas no con fuerza, sino con perseverancia.', author: 'Samuel Johnson' },
    { id: 76, quote: 'Apunta a la luna. Incluso si fallas, aterrizarás entre las estrellas.', author: 'Les Brown' },
    { id: 77, quote: 'Sé tan bueno que no puedan ignorarte.', author: 'Steve Martin' },
    { id: 78, quote: 'A veces, la caída te enseña a volar.', author: 'Anónimo' },
    { id: 79, quote: 'Los límites sólo están en tu mente.', author: 'Anónimo' },
    { id: 80, quote: 'Si puedes visualizarlo, puedes lograrlo.', author: 'Joel Osteen' },
    { id: 81, quote: 'El éxito no se logra solo con cualidades especiales. Es sobre todo un trabajo de constancia.', author: 'Angela Duckworth' },
    { id: 82, quote: 'La inspiración existe, pero tiene que encontrarte trabajando.', author: 'Pablo Picasso' },
    { id: 83, quote: 'No sueñes tu vida, vive tu sueño.', author: 'Anónimo' },
    { id: 84, quote: 'La única forma de hacer un gran trabajo es amar lo que haces.', author: 'Steve Jobs' },
    { id: 85, quote: 'Nadie que haya dado lo mejor de sí lo ha lamentado.', author: 'George Halas' },
    { id: 86, quote: 'Empieza donde estás. Usa lo que tienes. Haz lo que puedas.', author: 'Arthur Ashe' },
    { id: 87, quote: 'Tus sueños no tienen fecha de caducidad.', author: 'Anónimo' },
    { id: 88, quote: 'Haz que cada día cuente.', author: 'Muhammad Ali' },
    { id: 89, quote: 'El único lugar donde el éxito viene antes del trabajo es en el diccionario.', author: 'Vidal Sassoon' },
    { id: 90, quote: 'Los grandes logros requieren grandes sacrificios.', author: 'James Allen' },
    { id: 91, quote: 'Nunca es demasiado tarde para comenzar de nuevo.', author: 'Jack Kornfield' },
    { id: 92, quote: 'Las oportunidades no pasan, las creas.', author: 'Chris Grosser' },
    { id: 93, quote: 'Cree que puedes, y ya estás a mitad de camino.', author: 'Theodore Roosevelt' },
    { id: 94, quote: 'La pasión es energía. Siente el poder que viene de centrarte en lo que te entusiasma.', author: 'Oprah Winfrey' },
    { id: 95, quote: 'Haz lo que amas, ama lo que haces.', author: 'Ray Bradbury' },
    { id: 96, quote: 'Lo que haces hoy puede mejorar todos tus mañanas.', author: 'Ralph Marston' },
    { id: 97, quote: 'No es la carga lo que te rompe, sino la forma en que la llevas.', author: 'Lou Holtz' },
    { id: 98, quote: 'Los desafíos hacen la vida interesante, superarlos la hace significativa.', author: 'Joshua Marine' },
    { id: 99, quote: 'Nadie puede hacerte sentir inferior sin tu consentimiento.', author: 'Eleanor Roosevelt' },
    { id: 100, quote: 'Todo lo que siempre has querido está al otro lado del miedo.', author: 'George Addair' }
];

export default async function seedQuotesIfEmpty() {
    try {
        const count = await Quote.count();
        if (count === 0) {
            await Quote.bulkCreate(initialQuotes);
            console.log('Frases insertadas correctamente');
        } else {
            console.log('La tabla Quotes ya contiene datos. No se insertó nada.');
        }
    } catch (err) {
        console.error('Error al insertar frases:', err);
    }
}
